<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SCANIA</title>
  <style>
    #video-background {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: -1;
      overflow: hidden;
    }
    
    #video-background video {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      min-width: 100%;
      min-height: 100%;
      object-fit: cover;
      width: auto;
      height: auto;
    }
    
    .content {
      position: relative;
      z-index: 1;
      text-align: center;
      padding: 50px;
    }
    
    .heading {
      font-size: 4rem;
      font-weight: bold;
      color: #ffffff;
      margin-bottom: 20px;
      font-family: 'Times New Roman', Times, serif;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
    }

    .heading span {
      color: goldenrod;
    }
    
    .text {
      font-size: 2rem;
      color: #ffffff;
      margin-bottom: 30px;
      line-height: 1.5;
      text-shadow: 1px 1px 2px rgba(0, 0, 255, 0.2);
    }
    
    .button {
      display: inline-block;
      padding: 10px 20px;
      font-size: 22px;
      color: #ffffff;
      background-color: #1b3bee;
      border: none;
      cursor: pointer;
      transition: background-color 0.3s ease;
      text-decoration: none;
      border-radius: 10px;
      font-weight: bold;
    }
    
    .button:hover {
      background-color: #040e45;
    }
  </style>
  <script>
    window.addEventListener('resize', resizeVideo);

    function resizeVideo() {
      const video = document.getElementById('background-video');
      const videoContainer = document.getElementById('video-background');

      if (video && videoContainer) {
        const videoWidth = video.videoWidth;
        const videoHeight = video.videoHeight;
        const containerWidth = videoContainer.offsetWidth;
        const containerHeight = videoContainer.offsetHeight;
        const containerRatio = containerWidth / containerHeight;
        const videoRatio = videoWidth / videoHeight;

        if (containerRatio > videoRatio) {
          video.style.width = '100%';
          video.style.height = 'auto';
        } else {
          video.style.width = 'auto';
          video.style.height = '100%';
        }
      }
    }

    document.addEventListener('DOMContentLoaded', resizeVideo);
  </script>
</head>
<body>
  <div id="video-background">
    <video id="background-video" src="images/Scania2.mp4" autoplay loop muted></video>
  </div>
  <div class="content">
    <h1 class="heading">Welcome to <span>SCANIA</span></h1>
    <p class="text">Scania is an innovative website utilizing ResNet-50 to analyze chest X-ray (CXR) images.
         It provides advanced image processing for improved diagnosis of chest conditions;
          however, it's important to note that the results generated by the website may not be
           entirely conclusive and should be interpreted by a trained medical professional for accurate assessment.</p>
    <a href="login.php" class="button">Get Started</a>
 </div>
</body>
</html>
